//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPG
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KingdomFitnessEntities : DbContext
    {
        public KingdomFitnessEntities()
            : base("name=KingdomFitnessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GoiTap> GoiTaps { get; set; }
        public virtual DbSet<HoaDonThanhToan> HoaDonThanhToans { get; set; }
        public virtual DbSet<HoiVien> HoiVien { get; set; }
        public virtual DbSet<PT> PTs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
    }
}
