//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPG
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonThanhToan
    {
        public int MaHD { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public int MaHV { get; set; }
        public int MaGoi { get; set; }
        public Nullable<int> MaPT { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayHetHan { get; set; }
        public decimal TongTien { get; set; }
    
        public virtual GoiTap GoiTap { get; set; }
        public virtual HoiVien HoiVien { get; set; }
        public virtual PT PT { get; set; }
    }
}
